site_name: NYAML Documentation
site_description:
  The documentation for the NYAML tool which is a converter tool to transcode NeXus schema from YAML to XML (.nxdl.xml).
site_author: "The FAIRmat authors"
repo_url: https://github.com/FAIRmat-NFDI/nyaml
nav:
  - Home: index.md
  - Tutorial: tutorials.md
  - How-To-Guide : howto.md
  - Explanation: explanations.md
  - Reference: references.md
plugins:
  - mkdocstrings
  - mermaid2
  - search
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - md_in_html
  - mkdocs-click
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: "material"
  palette:
    primary: "#2A4CDF"
    accent: "#008A67"
  font:
    text: "Titillium Web"
  logo: assets/nomad-plugin-logo.png
  favicon: assets/favicon.png
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.bottom
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tabs.copy
    - content.code.annotation
  icon:
    repo: fontawesome/brands/github

extra:
  generator: false
  # homepage: https://fairmat-nfdi.github.io/pynxtools/

use_directory_urls: false
extra_css:
  - stylesheets/extra.css
