site_name: NYAML Docs
site_description:
  The documentation for NYAML tools that is a converter tools to transcode  NeXus schema from YAML format to the XML format (.nxdl.xml).
site_author: "The FAIRmat authors"
nav:
  - Home: index.md
  - Tutorial: tutorials.md
  - How-To-Guide : how_to_guide.md
  - Reference: references.md
  - Explanation: explanations.md
plugins:
  - mkdocstrings
  - mermaid2
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: "material"
  icon:
    admonition:
      note: octicons/tag-16

extra_css:
  - stylesheets/extra.css
