name: build_and_deploy_docs
on:
  push:
    branches: [MyDoc]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Check Spell
        run: |
          npm install -g cspell
          cspell --config ./cspell.config.yaml "docs/**/*.md"

          if [[ $? -ne 0 ]]; then
            echo "Docs contain spelling errors. Please fix them before deploying. Exiting."
            exit 1
          fi
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install ".[docs]"
      - run: mkdocs gh-deploy --force --remote-branch gh-pages