name: Build and deploy mkdocs

on:
  push:
    branches:
      - main

env:
  python-version: 3.12

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Git credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv and set the python version to ${{ env.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.python-version }}

      - name: Set cache key suffix
        id: cache_key
        run: echo "value=$(date --utc '+%V')" >> "$GITHUB_OUTPUT"

      - name: Cache mkdocs-material environment
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ steps.cache_key.outputs.value }} # Restore content with the same cache key
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: |
          uv pip install ".[docs]"

      - name: Build and deploy
        run: |
          mkdocs gh-deploy --force --remote-branch gh-pages